/*
 * Sonar .NET Plugin :: ReSharper
 * Copyright (C) 2013 John M. Wright
 * dev@sonar.codehaus.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02
 */

package org.sonar.plugins.csharp.resharper;

import org.apache.commons.io.IOUtils;
import org.codehaus.staxmate.SMInputFactory;
import org.codehaus.staxmate.in.SMHierarchicCursor;
import org.codehaus.staxmate.in.SMInputCursor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.sonar.api.BatchExtension;
import org.sonar.api.batch.SensorContext;
import org.sonar.api.resources.Project;
import org.sonar.api.rules.Rule;
import org.sonar.api.rules.RuleFinder;
import org.sonar.api.rules.RuleQuery;
import org.sonar.api.rules.Violation;
import org.sonar.api.utils.SonarException;
import org.sonar.plugins.dotnet.api.DotNetResourceBridges;
import org.sonar.plugins.dotnet.api.microsoft.MicrosoftWindowsEnvironment;
import org.sonar.plugins.dotnet.api.microsoft.VisualStudioProject;
import org.sonar.plugins.dotnet.api.microsoft.VisualStudioSolution;
import org.sonar.plugins.dotnet.api.utils.ResourceHelper;
import org.sonar.plugins.dotnet.api.utils.StaxParserUtils;

import javax.xml.stream.XMLStreamException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;

/**
 * Parses the reports generated by a ReSharper analysis.
 */
public class ReSharperResultParser implements BatchExtension {

    private static final Logger LOG = LoggerFactory.getLogger(ReSharperResultParser.class);

    private final VisualStudioSolution vsSolution;
    private VisualStudioProject vsProject;
    private Project project;
    private SensorContext context;
    private RuleFinder ruleFinder;
    private String repositoryKey;

    /**
     * Constructs a @link{ReSharperResultParser}.
     */
    public ReSharperResultParser(MicrosoftWindowsEnvironment env, Project project, SensorContext context, RuleFinder ruleFinder,
                                 DotNetResourceBridges dotNetResourceBridges, ResourceHelper resourceHelper) {
        super();

        this.vsSolution = env.getCurrentSolution();
        if (vsSolution == null) {
            // not a .NET project
            return;
        }

        this.vsProject = vsSolution.getProjectFromSonarProject(project);

        this.project = project;
        this.context = context;
        this.ruleFinder = ruleFinder;

        String projLanguage =  project.getLanguageKey();
        repositoryKey = ReSharperConstants.REPOSITORY_KEY + "-" + projLanguage;

    }

    /**
     * Parses a processed violation file.
     *
     * @param file
     *          the file to parse
     */
    public void parse(File file) {

        SMInputFactory inputFactory = StaxParserUtils.initStax();
        FileInputStream fileInputStream = null;
        try {
            fileInputStream = new FileInputStream(file);
            SMHierarchicCursor cursor = inputFactory.rootElementCursor(new InputStreamReader(fileInputStream, project.getFileSystem().getSourceCharset()));
            SMInputCursor mainCursor = cursor.advance().childElementCursor();
            while (mainCursor.getNext() != null) {

                String nodeName =mainCursor.getQName().getLocalPart();

                if (nodeName.equals("Issues")) {
                    parseIssuesBloc(mainCursor);
                }
            }
            cursor.getStreamReader().closeCompletely();
        } catch (XMLStreamException e) {
            throw new SonarException("Error while reading ReSharper result file: " + file.getAbsolutePath(), e);
        } catch (FileNotFoundException e) {
            throw new SonarException("Cannot find ReSharper result file: " + file.getAbsolutePath(), e);
        } finally {
            IOUtils.closeQuietly(fileInputStream);
        }
    }

    private void parseIssuesBloc(SMInputCursor cursor) throws XMLStreamException {
        // Cursor on <Issues>
        SMInputCursor projectsCursor = cursor.childElementCursor("Project");
        while (projectsCursor.getNext() != null) {

            //compare with vsProject to only run the current project's block
            String projectName = projectsCursor.getAttrValue("Name");
            String thisName =  vsProject.getName();
            if (projectName.equals(thisName))  {
                parseProjectBloc(projectsCursor);
            } else {
                LOG.debug("Skipping project block due to name mismatch.  Currently analyzing '" + thisName +"', processing '" + projectName + "'");
            }
        }
    }


    private void parseProjectBloc(SMInputCursor projectCursor) throws XMLStreamException {
        // Cursor in on <Project>
        SMInputCursor issuesCursor = projectCursor.childElementCursor("Issue");
        while (issuesCursor.getNext() != null) {

            String ruleKey = "ReSharperInspectCode#" + issuesCursor.getAttrValue("TypeId");

            LOG.debug("Searching for rule '"+ruleKey+"' in repository '" + repositoryKey +"'");
            Rule currentRule = ruleFinder.find(RuleQuery.create().withRepositoryKey(repositoryKey).withConfigKey(ruleKey));
            if (currentRule != null) {
                LOG.debug("Rule found: " + ruleKey);
                createViolation(issuesCursor, currentRule);
            } else {
                LOG.warn("Could not find the following rule in the ReSharper rule repository: " + ruleKey);
            }
        }
    }



    private void createViolation(SMInputCursor violationsCursor, Rule currentRule) throws XMLStreamException {
        File sourceFile = new File(violationsCursor.getAttrValue("File"));

        try{
            LOG.debug("searching for sourceFile " + sourceFile.getCanonicalFile().getPath() + " - Exists: " + sourceFile.exists());
        }catch (Exception ex)
        {
            LOG.warn("Exception: " + ex.getMessage());
        }

        if (vsProject.contains(sourceFile)) {
            final org.sonar.api.resources.File sonarFile;
            sonarFile = org.sonar.api.resources.File.fromIOFile(sourceFile, project);

            Violation violation = Violation.create(currentRule, sonarFile);
            String lineNumber = violationsCursor.getAttrValue("Line");
            if (lineNumber != null) {
                violation.setLineId(Integer.parseInt(lineNumber));
            }

            String message = violationsCursor.getAttrValue("Message");
            violation.setMessage(message.trim());
            context.saveViolation(violation);
        } else {
            LOG.warn("Violation could not be saved, associated file not referenced in VS project" + sourceFile);
        }
    }

}
